config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#about'
  get    'signup'    => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'     => 'sessions#create'
  delete 'logout'    => 'sessions#destroy'

  get 'about' => 'static_pages#about'
  get 'leadership' => 'static_pages#leadership'
  get 'competences' => 'static_pages#competences'
  get 'statistics' => 'static_pages#statistics'
  get 'projects' => 'static_pages#projects'
  get 'companies' => 'static_pages#companies'
  get 'eae' => 'static_pages#eae'
  get 'sezam' => 'static_pages#sezam'
  get 'pem' => 'static_pages#pem'
  get 'gem' => 'static_pages#gem'
  get 'promcenter' => 'static_pages#promcenter'

  resources :users, only: [:show, :index, :create, :edit, :update, :destroy] do
    get 'topics' => 'users#topics'
    get 'messages' => 'users#messages'
  end

  resources :forums, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :topics, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :messages, only: [:create, :edit, :update, :destroy]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :account_activations, only: [:edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :topic

  validates :content, presence: { message: "Сообщение не может быть пустым" },
  length: { in: 1..5000, message: "В сообщении должно быть от 1 до 5000 символов"}
  validates :user_id, presence: { message: "Сообщение должно принадлежать пользователю" }
  validates :topic_id, presence: { message: "Сообщение должно принадлежать теме" }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in_user, only: [:create, :edit, :update, :destroy]
  before_action :correct_user_m, only: [:edit, :update, :destroy]

  def create
    @message = current_user.messages.new(message_params)
    flash[:danger] = "Сообщение должно содержать от 1 до 5000 символов!" unless @message.save
    redirect_to forum_topic_url(params[:forum_id], params[:id])
  end

  def destroy
      @message = Message.find(params[:id]).destroy
      redirect_back fallback_location: forum_topic_url(Topic.find(@message.topic_id).forum_id, @message.topic_id)
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    if @message.update_attributes(update_params)
      flash[:info] = "Сообщение успешно изменено!"
      redirect_to forum_topic_url(Topic.find(@message.topic_id).forum_id, @message.topic_id)
    else
      render 'edit'
    end
  end

  private

  def message_params
    m_params = params.require(:message).permit(:content)
    m_params[:topic_id] = params[:id]
    t = Topic.find(params[:id]).restricted
    if t == "mod"
      m_params[:restricted] = :mod
    elsif t == "employee"
      m_params[:restricted] = :employee
    end
    m_params
  end

  def update_params
    m_params = params.require(:message).permit(:content, :redacted_by, :restricted)
    m_params[:redacted_by] = current_user.id
    m_params
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
  def correct_user_m
    @message = Message.find(params[:id])
    @user = User.find(@message.user_id)
    unless ((@user == current_user) || @current_user.admin? || @current_user.mod?)
        flash[:danger] = "У вас нет достаточных прав доступа!"
        redirect_back fallback_location: forums_url
    end
  end
end

app/views/layouts/message/_message_mini.html.erb
<% @messages.each do |m| %>

<div class="message-mini">

  <div class="message-mini-body">
    <%= simple_format(m.content, {}, wrapper_tag: "span") %>
    <% if !m.redacted_by.nil? %>
      <div class="pop-up">
        <div class="pop-up-content">
          <span>Редактировано: <%= User.find(m.redacted_by).name %></span><br>
          <span>Дата: <%= m.updated_at.strftime("%d/%m/%Y - %H:%M:%S") %></span>
        </div>
        <div class="pop-up-trigger"></div>
      </div>
    <% end %>
  </div>

  <div class="message-mini-footer">
    <%= link_to m.user.name, user_path(m.user) %>, <%= m.created_at.strftime("%d/%m/%Y - %H:%M:%S") %>
    <% if current_user && (@current_user.admin? || @current_user.mod? || @current_user.id == m.user_id) %>
      <span>
        <%= link_to "Редактировать", edit_message_path(m) %>
        <%= link_to "Удалить", message_path(m, :forum_id => params[:forums_id]), method: :delete, data: { confirm: "Вы уверены, что хотите удалить это сообщение?"} %>
      </span>
    <% end %>
  </div>

</div>

<% end %>

app/views/layouts/message/_new_form.html.erb
<%= form_for @message do |f| %>
  <%= render 'shared/error_messages/message'%>
  <%= hidden_field_tag :forum_id, params[:forum_id] %>
  <%= hidden_field_tag :id, params[:id] %>
  <%= f.text_area :content %>
  <%= f.submit "Отправить сообщение" %>
<% end %>

app/views/layouts/message/_update_form.html.erb
<div class="message-edit-form">
<%= form_for @message, method: :patch do |f| %>

  <h2>Редактирование сообщения</h2>
  <div class="divider"></div>

  <%= render 'shared/error_messages/message'%>

  <%= f.text_area :content %>

  <%= f.submit "Обновить сообщение" %>
<% end %>
</div>

app/views/layouts/message/_user_message_mini.html.erb
<% @messages.each_with_index do |m, index| %>

<div class="message-mini">

  <div class="message-mini-body">
    <%= if (m.content.length <= 200)
      simple_format(m.content, {}, wrapper_tag: "span")
    else
      simple_format(m.content[0,199] + "...", {}, wrapper_tag: "span")
    end %>

    <% if !m.redacted_by.nil? %>
      <div class="pop-up">
        <div class="pop-up-content">
          <span>Редактировано: <%= User.find(m.redacted_by).name %></span><br>
          <span>Дата: <%= m.updated_at.strftime("%d/%m/%Y - %H:%M:%S") %></span>
        </div>
        <div class="pop-up-trigger"></div>
      </div>
    <% end %>
  </div>

  <div class="message-mini-footer">
    <div class="info">
      <% t = Topic.find(m.topic_id) %>
      <% f = Forum.find(t.forum_id) %>
      <%= link_to name_with_restriction(f), forum_path(f.id) %>,
      <%= link_to name_with_restriction(t), forum_topic_path(f.id, m.topic_id) %>,
      <%= m.created_at.strftime("%d/%m/%Y - %H:%M:%S") %>
    </div>
    <span>
      <%= link_to "Перейти", forum_topic_path(f.id, m.topic_id), :page => find_page(20, t.messages.index(m) + 1) %>
      <% if current_user && (@current_user.admin? || @current_user.mod? || @current_user.id == m.user_id) %>
        <%= link_to "Редактировать", edit_message_path(m) %>
        <%= link_to "Удалить", message_path(m), method: :delete, data: { confirm: "Вы уверены, что хотите удалить это сообщение?"} %>
      <% end %>
    </span>
  </div>

</div>

<% end %>