config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#about'
  get    'signup'    => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'     => 'sessions#create'
  delete 'logout'    => 'sessions#destroy'

  get 'about' => 'static_pages#about'
  get 'leadership' => 'static_pages#leadership'
  get 'competences' => 'static_pages#competences'
  get 'statistics' => 'static_pages#statistics'
  get 'projects' => 'static_pages#projects'
  get 'companies' => 'static_pages#companies'
  get 'eae' => 'static_pages#eae'
  get 'sezam' => 'static_pages#sezam'
  get 'pem' => 'static_pages#pem'
  get 'gem' => 'static_pages#gem'
  get 'promcenter' => 'static_pages#promcenter'

  resources :users, only: [:show, :index, :create, :edit, :update, :destroy] do
    get 'topics' => 'users#topics'
    get 'messages' => 'users#messages'
  end

  resources :forums, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :topics, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :messages, only: [:create, :edit, :update, :destroy]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :account_activations, only: [:edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def leadership
  end

  def competences
  end

  def statistics
  end

  def projects
  end

  def companies
  end

  def eae
  end

  def sezam
  end

  def pem
  end

  def gem
  end

  def promcenter
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="static-container">
  <div class="static-wrapper about">
    <div class="section-wrapper">
      <div class="info-panel info-panel-1">
        <div>
        <h2>Кратко о холдинге</h2>
        <span>В целях сплочения профессиональных кадров и формирования конкуренто-способного предложения на рынке строительного и консультационного инжиниринга, в 2006 году создана сильная команда профессионалов - Холдинг "Энергоатоминжиниринг", управляемый одноименной компанией и объединяющий четыре крупные строительно-монтажные организации.</span>
      </div>
      <div>
        <ul>
          <li>ОАО "Энергоатоминжиниринг"</li>
          <li> ОАО "Промэлектромонтаж"</li>
          <li>ЗАО "Гидроэлектромонтаж"</li>
          <li>АО "Севзапатоммонтаж"</li>
          <li>ЗАО "Промцентр"</li>
        </ul>
      </div>
      </div>

      <div class="info-panel info-panel-2">
        <h2>Состав холдинга</h2>
        <span>Сегодня в составе холдинга "Энергоатоминжиниринг" - 5 крупных компаний энерго-инжинирингового сектора, общее количество производственных активов - более 20 единиц, расположенных в 12 регионах России, а также за рубежом - в Иране и КНР. Численность профессионального кадрового состава холдинга - 3000 человек.</span>
      </div>

      <div class="info-panel info-panel-3">
        <h2>Основные принципы нашей работы</h2>
        <p><b>Надежное партнерство</b> - в нашей работе мы стремимся к долгосрочному и взаимовыгодному сотрудничеству с партнерами.</p>

        <p><b>Гарантированное качество</b> выполняемых работ обеспечивается:
        <ul>
          <li>многолетним успешным опытом работы на сооружении энергоблоков, в том числе и атомных электростанций, объектов промышленного и социального назначения;</li>
          <li>наличием лицензий на осуществление узкоспециализированных видов деятельности.</li>
        </ul>
        </p>

        <p><b>Профессионализм</b> - на наших предприятиях работают только профессионалы своего дела: нам удалось не только сохранить, но и пополнить кадровый состав специалистами "советской закалки", обладающими багажом фундаментальных знаний в области электроэнергетики и бесценным опытом работы на строительстве крупных АЭС и энергоблоков.</p>

        <p><b>Постоянное развитие</b> - мы ориентированы на непрерывное наращивание наших производственно-технических и интеллектуальных ресурсов, разработку и внедрение новейших технологий - чтобы быть лучшими в своем деле, чтобы отвечать потребностям времени, высоким запросам заказчика, а главное - интересам нашего конечного потребителя - общества.</p>
      </div>

      <div class="info-panel info-panel-4">
        <h2>Наши преимущества:</h2>
        <ul>
          <li>многолетний фундаментальный опыт работы по крупным энергетическим проектам в различных регионах России, бывшего Советского Союза и за рубежом;</li>
          <li>широкая сеть территориальных подразделений, собственных научно-технических центров и производственно-складских хозяйств по всей России - возможность в кратчайшие сроки создать "развернуть" техническую базу и выйти на строительную площадку;</li>
          <li>3 тысячи квалифицированных специалистов;</li>
          <li>наличие всех видов государственных лицензий и разрешений на осуществление деятельности по сооружению энергоблоков (производство специальных видов работ).</li>
        </ul>
      </div>

      <div class="info-panel info-panel-5">
        <h2>Кадровая политика</h2>
        <p>ОАО "Энергоатоминжиниринг" - многопрофильная организация, которую составляют работники разных уровней и специализации; работа в компании - это шанс реализовать себя, раскрыть свой потенциал, определить уровень своих запросов и возможностей, поскольку для реализации их практически нет внешних ограничений: всё в ваших руках.</p>
        <p>Работать у нас могут не только люди, умудрённые годами и опытом. Сотрудники должны быть готовы к непрерывному повышению квалификации: мы проводим корпоративные тренинги, обучаем молодых специалистов, всячески способствуем приобретению ими практического опыта.</p>
        <p><b>Телефон отдела кадров:</b> (495) 253-71-72, <b>Email для резюме:</b> lfb@vfp.ru</p>
      </div>

    </div>
  </div>
</div>

app/views/static_pages/companies.html.erb
<div class="static-container">
  <div class="static-wrapper companies">
    <div class="section-wrapper">
      <div class="info-panel info-panel-1">
        <%= image_tag "eae_logo.gif" %>
        <h2>ЗАО "ЭНЕРГОАТОМИНЖИНИРИНГ"</h2>
        <%= link_to "Подробнее >", eae_path %>
        <p>Управляющая инжиниринговая компания холдинга. Образована в 2006 году. Осуществляет комплексный инжиниринг проекта и возлагает на себя полную ответственность за сооружение объекта: от начала проектирования до пуска в эксплуатацию и сервисного обслуживания.</p>
        <p>
          <b>Адрес:</b> 123022, Москва, ул. Б. Декабрьская, д. 3; <b>телефон:</b> (495)785-55-82;<br>
          <b>факс:</b> (495)785-55-84; <b>email:</b> common@energo-holding.ru.
        </p>
      </div>

      <div class="info-panel info-panel-2">
        <%= image_tag "pem_logo.gif" %>
        <h2>ОАО "ПРОМЭЛЕКТРОМОНТАЖ" (ПЭМ)</h2>
        <%= link_to "Подробнее >", pem_path %>
        <p>Широкопрофильная строительно-монтажная компания, производящая монтаж электрогенераторов, основного и вспомогательного силового оборудования на электрических станциях всех типов, а также осуществляющая полное проектирование и строительство зданий и сооружений различного назначения.</p>
        <p>
          <b>Адрес:</b> 127238, Москва, Дмитровское ш., 71; <b>телефон:</b> (495)785-97-90;<br>
          <b>факс:</b> (495)480-33-00; <b>email:</b> info@pem.ru.
        </p>
      </div>

      <div class="info-panel info-panel-3">
        <%= image_tag "gem_logo.gif" %>
        <h2>ЗАО ТВП "ГИДРОЭЛЕКТРОМОНТАЖ" (ГЭМ)</h2>
        <%= link_to "Подробнее >", gem_path %>
        <p>Специализируется на монтаже кабельных электрических линий и электротехнических устройств, монтаже систем автоматизации технологических процессов АСУ ТП, выполнении пусконаладочных работ электротехнических устройств и систем автоматизации.</p>
        <p>
          <b>Адрес:</b> 123022, Москва, ул. Б. Декабрьская, д. 3, <b>телефон:</b> (495)785-55-82,<br>
          <b>факс:</b> (495)785-55-84, <b>email:</b> common@energo-holding.ru.
        </p>
      </div>

      <div class="info-panel info-panel-4">
        <%= image_tag "sezam_logo.gif" %>
        <h2>АО "СЕВЗАПАТОММОНТАЖ" (СЕЗАМ)</h2>
        <%= link_to "Подробнее >", sezam_path %>
        <p>Специализированное предприятие по монтажу тепломеханического оборудования и технологических трубопроводов, изготовлению и монтажу металлоконструкций, нестандартного оборудования, изготовлению трубопроводов для промышленности и энергетики.</p>
        <p>
          <b>Адрес:</b> 171841, Тверская область, г. Удомля, а/я 12; <b>телефон:</b> (48255)7-24-25;<br>
          <b>факс:</b> (48255)7-24-25; <b>email:</b> sezam@udomlya.ru.
        </p>
      </div>

      <div class="info-panel info-panel-5">
        <%= image_tag "promcentr_logo.gif" %>
        <h2>ЗАО "ПРОМЦЕНТР"</h2>
        <%= link_to "Подробнее >", promcenter_path %>
        <p>Специализированное предприятие по изготовлению и монтажу металлоконструкций, электрических изделий.</p>
        <p><b>Адрес:</b> 188537, Ленинградская область, г. Сосновый Бор, Копорское шоссе, д. 68;<br>
        <b>телефон:</b> (813-69)2-49-90; <b>факс:</b> (813-69)2-19-00; <b>email:</b> indcenter@sbor.ru.</p>
      </div>

    </div>
  </div>
</div>

app/views/static_pages/competences.html.erb
<div class="static-container">
  <div class="static-wrapper competences">
    <div class="section-wrapper">
      <div class="info-panel info-panel-1">
        <%= image_tag "competences_1.jpg" %>
        <h2>Основные направления деятельности</h2>
        <ul><b>Инжиниринговая проработка и строительство тепловых и атомных электростанций "под ключ":</b>

          <li>строительство тепловых и атомных электростанций "под ключ", включая проектные работы по объекту;</li>
          <li>услуги по инжинирингу и строительству электростанций с полной комплектацией строительными материалами и оборудованием.</li>
        </ul>

        <ul><b>Монтаж, наладка, ремонт и реконструкция электрического оборудования электростанций и промышленных предприятий:</b>
          <li>монтаж электрического оборудования тепловых и атомных электростанций, подстанций и промышленных предприятий;</li>
          <li>наладка электрического оборудования тепловых и атомных электростанций, подстанций и промышленных предприятий;</li>
          <li>ремонт и реконструкция электрического оборудования тепловых и атомных электростанций, подстанций и промышленных предприятий.</li>
        </ul>

        <ul><b>Монтаж, наладка, ремонт и реконструкция технологического оборудования электростанций и промышленных предприятий:</b>
          <li>монтаж технологического оборудования тепловых и атомных электростанций, котельных и промышленных предприятий;</li>
          <li>наладка технологического оборудования тепловых и атомных электростанций, котельных и энергетического оборудования промышленных предприятий;</li>
          <li>ремонт технологического оборудования электростанций, комплексная реконструкция энергетических объектов, восстановление объектов после стихийных бедствий и аварий.</li>
        </ul>

        <p>Строительство, монтаж, ремонт и реконструкция трубопроводов тепловых сетей.</p>
        <p>Строительство, монтаж, ремонт и реконструкция магистральных нефте- и газопроводов.</p>
      </div>

      <div class="info-panel info-panel-1">
        <%= image_tag "competences_2.jpg" %>
        <h2>Возможности и технические достижения</h2>
        <ul>
        <li>опыт электромонтажных работ на уникальных установках ядерных и исследовательских центров, головных блоках атомных станций;</li>
        <li>монтаж электростанций с турбогенераторами от 6 до 1500 мВА;</li>
        <li>монтаж специальных аккумуляторных и дизельных установок надёжного питания;</li>
        <li>монтаж ЛЭП до 330 кВ в условиях горного Алтая, пустыни Кызыл-Кум;</li>
        <li>монтаж распределительных подстанций с напряжением до 750 кВ;</li>
        <li>монтаж токопроводов и шинопроводов, электротехнического оборудования и распределительных сетей, контрольно-измерительных приборов и приборов радиоизотопной техники, научно-исследовательских и промышленных гамма-установок;</li>
        <li>монтаж и наладка электрооборудования от 110-330 и 750 кВ, включая трансформаторы единичной мощностью до 1250 кВА, мощные испытательные стенды напряжением 1150-1500 кВ, элегазовые выключатели;</li>
        <li>опыт работы на компрессорных станциях магистральных трубопроводов, а также на питающих и тяговых подстанциях железных дорог.</li>
        <ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/eae.html.erb
<div class="static-container">
  <div class="static-wrapper eae">
    <div class="section-wrapper">

      <div class="title">
        <h2>ЗАО "ЭНЕРГОАТОМИНЖИНИРИНГ"</h2>
      </div>

      <div class="info-panel info-panel-1">
        <%= image_tag "eae_1.jpg" %>
        <h2>Основной профиль деятельности</h2>
        <p>
          Управляющая компания Холдинга - ЗАО "Энергоатоминжиниринг" - представляет собой эффективное вертикально-интегрированное предприятие, способное оказать комплекс инжиниринговых услуг, предложить системный подход к организации и выполнению работ по сооружению атомных и тепловых энергоблоков, а также строительству иных промышленных и гражданских объектов "под ключ". Таким образом обеспечивается высокая степень унификации и стандартизации проекта, снижение затрат Заказчика на всех этапах составляет около 10% от стоимости объекта.
        </p>
      </div>

      <div class="info-panel info-panel-2">
        <%= image_tag "eae_2.jpg" %>
        <h2>Функции управления и виды выполняемых работ</h2>
        <ul>
          <li>руководство реализацией проекта с целью достижения его соответствия требованиям и условиям Заказчика;</li>
          <li>проектно-конструкторские работы, разработка спецификаций, закупка оборудования, компонентов и систем станции;</li>
          <li>выполнение строительно-монтажных работ и сдача объекта Заказчику;</li>
          <li>разработка необходимых документов для обеспечения получения разрешений и лицензий, включая руководства по эксплуатации, обоснование безопасности АЭС и т.д.;</li>
          <li>обеспечение качества и контроля качества;</li>
          <li>транспортировка крупногабаритного оборудования на площадку;</li>
          <li>создание инфраструктуры Генерального подрядчика на площадке;</li>
          <li>приемка всех поставок и услуг от субподрядных организаций.</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/gem.html.erb
<div class="static-container">
  <div class="static-wrapper gem">
    <div class="section-wrapper">

      <div class="title">
        <h2>ЗАО ТВП "ГИДРОЭЛЕКТРОМОНТАЖ" (ГЭМ)</h2>
      </div>

      <div class="info-panel info-panel-1">
        <%= image_tag "gem_1.jpg" %>
        <h2>О предприятии</h2>
        <p>
          Всесоюзная организация "Гидроэлектромонтаж" была создана в 1946 году. Суммарные результаты работы предприятия не имеют аналогов в истории отечественного и европейского энергостроительства. В 1994 году оно было преобразовано в ЗАО ТВП "Гидроэлектромонтаж" путем реорганизации обособленного структурного подразделения Тверского монтажного управления АООТ "Гидроэлектромонтаж", став фактическим преемником последнего. На сегодняшний день общая численность работников во всех подразделениях предприятия составляет 800 человек. Государство достойно оценивает работу специалистов и руководителей ТВП "ГЭМ". Только за последние 15 лет более 30 человек награждены государственными наградами Российской Федерации.
        </p>
      </div>

      <div class="info-panel info-panel-2">
        <%= image_tag "gem_2.jpg" %>
        <h2>Основной профиль деятельности</h2>
        <p>
          ТВП "ГЭМ" специализируется на монтаже кабельных электрических линий и электротехнических устройств, систем автоматизации технологических процессов АСУ ТП, монтаже тепломеханического оборудования и трубопроводов, а также на выполнении пусконаладочных работ электротехнических устройств и систем автоматизации и сварочных работ.<br>
          Промышленная база ТВП "ГЭМ" находится на территории промплощадки Калининской атомной электростанции. Предприятие располагает подъездными ж/д путями, имеет подготовленные открытые площадки для хранения оборудования. Производственная база представлена цехами: КИПиА, электромонтажных изделий, укрупнённой сборки электрооборудования, сварки; мастерскими: столярной, авторемонтной, полным операционно-складским хозяйством, гаражами для автотехники.
        </p>
      </div>

      <div class="info-panel info-panel-3">
        <%= image_tag "gem_3.jpg" %>
        <h2>Выполняемые виды работ</h2>
        <ul>
          <li>монтаж кабельных электрических линий и электротехнических устройств;</li>
          <li>монтаж систем автоматизации технологических процессов АСУ ТП;</li>
          <li>монтаж тепломеханического оборудования и трубопроводов;</li>
          <li>доизготовление и укрупнительная сборка оборудования и трубопроводов;</li>
          <li>сварочные работы;</li>
          <li>пусконаладочные работы электротехнических устройств и систем автоматизации;</li>
          <li>контроль качества продукции и работ;</li>
          <li>контроль качества основных материалов, сварных соединений оборудования и трубопроводов;</li>
          <li>разработка производственной технологической, контрольной и эксплуатационной документации.</li>
        </ul>
      </div>

      <div class="info-panel info-panel-4">
        <h2>Состав предприятия</h2>
        <p>
          <b>Дирекция:</b> ЗАО "Тверское предприятие Гидроэлектромонтаж", г. Удомля, Тверская область.<br>
          <b>Филиалы:</b> строительно-монтажное управление на АЭС "Бушер" (г. Бушер, Иран); строительно-монтажное управление (г. Волгодонск, Ростовская область).
        </p>
      </div>

      <div class="info-panel info-panel-5">
        <h2>Объекты</h2>
        <ul><b>ЗАО Тверское предприятие "Гидроэлектромонтаж" выполнило комплекс электро-монтажных и пусконаладочных работ на следующих объектах:</b>
          <li>1,2,3-й блоки Калининской АЭС</li>
          <li>3-й блок Кольской АЭС</li>
          <li>4-й блок Курской АЭС</li>
          <li>1-й блок Волгодонской АЭС</li>
          <li>Балаковская АЭС</li>
          <li>Смоленская АЭС</li>
        </ul>
      </div>

      <div class="info-panel info-panel-6">
        <h2>Возможности и технические достижения</h2>
        <p>
          Среди наивысших технических достижений - монтаж и наладка электрооборудования от 110-330 и 750 кВ, включая трансформаторы единичной мощностью до 1250 кВА, мощные испытательные стенды напряжением 1150-1500 кВ, элегазовые выключатели.<br>
          Специалисты ЗАО ТВП "ГЭМ" имеют опыт работы на компрессорных станциях магистральных трубопроводов, а также на питающих и тяговых подстанциях железных дорог.
        </p>
      </div>

      <div class="info-panel info-panel-7">
        <h2>Лицензии</h2>

        <ul><b>Лицензии Федеральной службы по экологическому, технологическому и атомному надзору:</b>
          <li>на сооружение, в части выполнения отдельных работ, атомной станции;</li>
          <li>на эксплуатацию, в части выполнения отдельных работ, атомной станции;</li>
          <li>на изготовление оборудования для атомных станций;</li>
          <li>на конструирование оборудования для атомных станций;</li>
          <li>на сооружение комплексов по переработке радиоактивных отходов, в части выполнения отдельных работ и предоставления услуг эксплуатирующей организации;</li>
          <li>на сооружение пунктов хранения радиоактивных отходов, в части выполнения отдельных работ и предоставления услуг эксплуатирующей организации.</li>
        </ul>

        <ul><b>Лицензии Ростехнадзора:</b>
          <li>на эксплуатацию взрывоопасных производственных объектов;</li>
          <li>на осуществление деятельности по изготовлению оборудования для подъёмных сооружений;</li>
          <li>на право осуществления деятельности на объектах котлонадзора;</li>
          <li>на право осуществления пусконаладочных работ оборудования подъёмных сооружений;</li>
          <li>на право разработки технологической документации для выполнения работ с использованием грузоподъёмных механизмов;</li>
          <li>на право осуществления деятельности по эксплуатации подъёмных приспособлений;</li>
          <li>на право осуществления деятельности по эксплуатации сосудов, работающих под давлением.</li>
        </ul>

        <ul><b>Лицензии Госстроя России:</b>
          <li>на строительство зданий и сооружений 1-го и 2-го уровней ответственности в соответствии с государственным стандартом;</li>
          <li>на проектирование зданий и сооружений 1-го и 2-го уровней ответственности в соответствии с государственным стандартом.</li>
        </ul>

        <ul><b>Лицензия Министерства энергетики России:</b>
          <li>на осуществление деятельности по эксплуатации электрических сетей.
        </ul>

        <ul><b>Лицензия Главного управления Государственной противопожарной службы МЧС России:</b>
          <li>на производство работ по монтажу, ремонту и обслуживанию средств обеспечения пожарной безопасности зданий и сооружений.</li>
        </ul>

        <ul><b>Свидетельства концерна "Росэнергоатом":</b>
          <li>об аккредитации на исполнение работ по ремонту оборудования атомных станций концерна "Росэнергоатом";</li>
          <li>об аккредитации на выполнение работ на объектах концерна "Росэнергоатом".</li>
        </ul>

      </div>

    </div>
  </div>
</div>

app/views/static_pages/promcenter.html.erb
<div class="static-container">
  <div class="static-wrapper promcenter">
    <div class="section-wrapper">

      <div class="title">
        <h2>ЗАО "ПРОМЦЕНТР"</h2>
      </div>

      <div class="info-panel info-panel-1">
        <%= image_tag "promcentr_1.jpg" %>
        <h2>О предприятии</h2>
        <p>
          ЗАО "Промцентр" находится в промышленной зоне г. Сосновый Бор Ленинградской области. Город Сосновый Бор имеет развитую инфраструктуру, градообразующим предприятием является ЛАЭС—Ленинградская атомная электростанция. К предприятию также подходят железнодорожные пути, что дает возможность оперативно отгружать продукцию не только автомобильным, но и железнодорожным транспортом. Грузовое оборудование предприятия позволяет перемещать грузы до 7 тонн.
        </p>
      </div>

      <div class="info-panel info-panel-2">
        <%= image_tag "promcentr_2.jpg" %>
        <h2>Виды выпускаемой продукции</h2>
        <ul>
          <li>кабельные короба;</li>
          <li>сейсмостойкие стеллажи;</li>
          <li>съёмные и несъёмные металлические опалубки по чертежам заказчика;</li>
          <li>металлические окна;</li>
          <li>декоративные ограды и решетки;</li>
          <li>канализационно-насосные станции;</li>
          <li>конвейерная покраска изделий;</li>
          <li>пескоструйная обработка;</li>
          <li>металлические стеллажи для хранения готовой продукции.</li>
        </ul>
      </div>

      <div class="info-panel info-panel-3">
        <%= image_tag "promcentr_3.jpg" %>
        <h2>Лицензии и сертификаты</h2>
        <ul>
          <li>лицензия на изготовление оборудования для атомных станций;</li>
          <li>лицензия на строительство зданий и сооружений I и II уровней ответственности в соответствии с государственными стандартами;</li>
          <li>сертификат соответствия "Устройства комплектные низковольтные".</li>
        </ul>
      </div>

      <div class="info-panel info-panel-1">
        <%= image_tag "promcentr_4.jpg" %>
        <h2>Объекты</h2>
        <ul><b>ЗАО «Промцентр» изготовило и поставило оборудование на следующие объекты:</b>
          <li>Ленинградская АЭС</li>
          <li>Билибинская АЭС</li>
          <li>Балакановская АЭС</li>
          <li>Волгодонская АЭС</li>
          <li>Курская АЭС</li>
          <li>Ростовская АЭС</li>
          <li>Иран АЭС "Бушер-1"</li>
          <li>ОАО "Промэлектромонтаж" (Холдинг "Энергоатоминжиниринг")</li>
          <li>ОАО "СЭМ"</li>
          <li>СМСУ-80</li>
          <li>СМНУ "КВАРС"</li>
          <li>СМУП "АТП"</li>
          <li>Ломоносовский РУС</li>
          <li>СУ 303 УССТ-3</li>
          <li>Строительная компания «Ораниенбаум»</li>
          <li>ФГУП СНПО «Элерон»</li>
          <li>ФГУП «Радон»</li>
          <li>ООО «Проба»</li>
          <li>ЗАО «Балткабель»</li>
          <li>ЗАО «Юнимет»</li>
          <li>ОАО Волгоградская фирма "Нефтемашзавод"</li>
          <li>Тверское предприятие ЗАО «Гидроэлектромонтаж»</li>
          <li>Санкт-Петербургский филиал "СевЗапэлектросетьстрой"</li>
          <li>ЗАО «CONSYS»</li>
        </ul>
      </div>

    </div>
  </div>
</div>