config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#about'
  get    'signup'    => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'     => 'sessions#create'
  delete 'logout'    => 'sessions#destroy'

  get 'about' => 'static_pages#about'
  get 'leadership' => 'static_pages#leadership'
  get 'competences' => 'static_pages#competences'
  get 'statistics' => 'static_pages#statistics'
  get 'projects' => 'static_pages#projects'
  get 'companies' => 'static_pages#companies'
  get 'eae' => 'static_pages#eae'
  get 'sezam' => 'static_pages#sezam'
  get 'pem' => 'static_pages#pem'
  get 'gem' => 'static_pages#gem'
  get 'promcenter' => 'static_pages#promcenter'

  resources :users, only: [:show, :index, :create, :edit, :update, :destroy] do
    get 'topics' => 'users#topics'
    get 'messages' => 'users#messages'
  end

  resources :forums, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :topics, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :messages, only: [:create, :edit, :update, :destroy]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :account_activations, only: [:edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :reset_token, :remember_token, :activation_token
  has_many :forums, :dependent => :destroy
  has_many :topics, :dependent => :destroy
  has_many :messages, :dependent => :destroy
  before_save {self.email.downcase!}
  before_create :create_activation_digest

  VALID_NAME_REGEX = /\A[a-zA-Z\d_]+\z/
  validates :name, presence: { message: "Имя не может быть пустым" },
  length: { in: 3..20, message: "В имени должно быть от 3 до 20 символов"},
  format: { with: VALID_NAME_REGEX, message: "В имени могут использоваться латинские буквы, цифры и нижние подчёркивания" },
  uniqueness: {case_sensitive: false, message: "Такое имя уже существует"}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: { message: "Почта не может быть пустой" },
  length: { in: 5..100, message: "В почте должно быть от 5 до 100 символов" },
  format: { with: VALID_EMAIL_REGEX, message: "Почта введена некорректно" },
  uniqueness: { case_sensitive: false, message: "Такая почта уже существует"}

  has_secure_password
  validates :password, length: { minimum: 8, message: "В пароле должно быть не менее восьми символов" }, allow_blank: true

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def password_reset_expired?
    reset_sent_at < 1.hours.ago
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def create_remember_digest
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget_remember_digest
    update_attribute(:remember_digest, nil)
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def admin?
    if self.role == "admin"
      return true
    else
      return false
    end
  end

  def mod?
    if self.role == "mod"
      return true
    else
      return false
    end
  end

  def employee?
    if self.role == "employee"
      return true
    else
      return false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy,
                                        :topics, :messages]
  before_action :correct_user, only: [:edit, :update]
  before_action :administrator, only: :destroy


  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "На вашу почту выслано письмо с ссылкой для активации аккаунта."
      redirect_to forums_url
    else
      render 'new'
    end
  end

  def index
    @users = User.paginate(:page => params[:page], :per_page => 30)
  end

  def edit
    @user = User.find(params[:id])
  end

  def topics
    @user = User.find(params[:user_id])
    @topics = extract_topics(@user).paginate(:page => params[:page], :per_page => 10)
  end

  def messages
    @user = User.find(params[:user_id])
    @messages = extract_messages(@user).paginate(:page => params[:page], :per_page => 10)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(update_params)
      flash[:success] = "Профиль успешно обновлён!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_params
    upd = params.require(:user).permit(:name, :email, :about, :role, :password, :password_confirmation)
    upd[:redacted_by] = current_user.id
    upd
  end

  def extract_topics user
    if current_user != nil && (@current_user.admin? || @current_user.mod?)
      topics = @user.topics.all
    elsif @current_user != nil && @current_user.employee?
      topics = @user.topics.where(restricted: ["employee", "user"])
    else
      topics = @user.topics.where(restricted: "user")
    end
    topics
  end

  def extract_messages user
    if current_user != nil && (@current_user.admin? || @current_user.mod?)
      messages = @user.messages.all
    elsif @current_user != nil && @current_user.employee?
      messages = @user.messages.where(restricted: ["employee", "user"])
    else
      messages = @user.messages.where(restricted: "user")
    end
    messages
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Пожалуйста, войдите на форум!"
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    unless ((@user == current_user) || @current_user.admin? || @current_user.mod?)
        flash[:danger] = "У вас нет прав доступа к этой странице!"
        redirect_back fallback_location: forums_url
    end
  end

  def administrator
    unless current_user.admin?
        flash[:danger] = "У вас нет прав доступа для этого действия!"
        redirect_back fallback_location: forums_url
    end
  end

end

app/views/layouts/user/_registration_form.html.erb
<div class="reg-form">
<%= form_for @user do |f| %>
  <h2>Регистрация</h2>
  <div class="divider"></div>

  <%= render 'shared/error_messages/user'%>

  <%= f.label :name, "Имя пользователя:" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, "Электронная почта:" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, "Пароль:" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, "Подтверждение пароля:" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit "Зарегистрироваться", class: "btn btn-primary dark-blue" %>
<% end %>
</div>

app/views/layouts/user/_update_form.html.erb
<div class="user-update-form">
  <%= form_for @user do |f| %>
    <%= render 'shared/error_messages/user' %>

    <%= f.label :name, "Имя пользователя:" %>
    <%= f.text_field :name %>

    <%= f.label :about, "Рассказать о себе:" %>
    <%= f.text_area :about %>

    <% if current_user.admin? %>

      <% if @user.admin? %>
        <label class="disabled">Привилегии:</label>
        <select disabled class="disabled">
          <option>Администратор</option>
        </select>

      <% else %>
        <%= f.label :role, "Привилегии:" %>
        <%= f.select :role, [["Модератор", :mod ], ["Сотрудник", :employee], ["Обычный пользователь", :user]] %>

      <% end %>

      <%= f.label :password, "Пароль:" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Подтверждение пароля:" %>
      <%= f.password_field :password_confirmation %>

    <% else %>

      <label class="disabled">Привилегии:</label>
      <select disabled class="disabled"><option>
        <% if @user.mod? %>
          Модератор
        <% elsif @user.employee? %>
          Сотрудник
        <% else  %>
          Пользователь
        <% end %>
      </option></select>

      <% if @user == @current_user %>
        <%= f.label :password, "Пароль:" %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation, "Подтверждение пароля:" %>
        <%= f.password_field :password_confirmation %>
      <% else %>

        <label class="disabled">Пароль:</label>
        <input type="text" disabled class="disabled"></input>
        <label class="disabled">Подтверждение пароля:</label>
        <input type="text" disabled class="disabled"></input>
      <% end %>
    <% end %>

    <%= f.submit "Обновить профиль" %>
  <% end %>
</div>

app/views/layouts/user/_user_profile_menu.html.erb
<div class="user-profile-menu">

    <div class="pop-up">
      <div class="pop-up-content">
        <span>Активирован:
          <%= if @user.activated
                @user.activated_at.strftime("%d/%m/%Y - %H:%M:%S")
              else
                "Нет"
              end %>
        </span><br>
        <% if !@user.redacted_by.nil? %>
          <span>Редактирован: <%= User.find(@user.redacted_by).name %></span><br>
          <span>Дата: <%= @user.updated_at.strftime("%d/%m/%Y - %H:%M:%S") %></span>
        <% end %>
      </div>
      <div class="pop-up-trigger"></div>
    </div>

  <div class="user-menu-img"></div>
  <div class="user-menu-name"><span><%= @user.name %></span></div>
  <div class="user-menu-status"><span>
    <% if @user.admin? %>
      Администратор
    <% elsif @user.mod? %>
      Модератор
    <% elsif @user.employee? %>
      Сотрудник
    <% else %>
      Пользователь
    <% end %>
  </span></div>

  <ul>
    <li>
      <%= link_to "О пользователе", @user %>
    </li>

    <li>
      <%= link_to "Сообщения", user_messages_path(@user) %>
      <div class="counter">
        <span><%= @user.messages.count %></span>
      </div>
    </li>

    <li>
    <%= link_to "Темы", user_topics_path(@user) %>
    <div class="counter">
      <span><%= @user.topics.count %></span>
    </div>
    </li>

    <% if (current_user == @user) || current_user.admin? || (current_user.mod? && !@user.admin?) %>
      <li>
        <%= link_to "Настройки", edit_user_path(@user) %>
      </li>
    <% else %>
      <li><a class="disabled">Настройки</a></li>
    <% end %>

    <% if current_user && current_user.admin? && !@user.admin? %>
      <li>
        <%= link_to "Удалить", user_path(@user), method: :delete, data: { confirm: "Вы уверены, что хотите удалить этого пользователя?"} %>
      </li>
    <% else %>
      <li><a class="disabled">Удалить</a></li>
    <% end %>

  </ul>
</div>