config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#about'
  get    'signup'    => 'users#new'
  get    'login'     => 'sessions#new'
  post   'login'     => 'sessions#create'
  delete 'logout'    => 'sessions#destroy'

  get 'about' => 'static_pages#about'
  get 'leadership' => 'static_pages#leadership'
  get 'competences' => 'static_pages#competences'
  get 'statistics' => 'static_pages#statistics'
  get 'projects' => 'static_pages#projects'
  get 'companies' => 'static_pages#companies'
  get 'eae' => 'static_pages#eae'
  get 'sezam' => 'static_pages#sezam'
  get 'pem' => 'static_pages#pem'
  get 'gem' => 'static_pages#gem'
  get 'promcenter' => 'static_pages#promcenter'

  resources :users, only: [:show, :index, :create, :edit, :update, :destroy] do
    get 'topics' => 'users#topics'
    get 'messages' => 'users#messages'
  end

  resources :forums, only: [:index, :show, :edit, :create, :update, :destroy] do
      resources :topics, only: [:show, :new, :create, :edit, :update, :destroy]
  end

  resources :messages, only: [:create, :edit, :update, :destroy]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :account_activations, only: [:edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  belongs_to :forum
  has_many :messages, :dependent => :destroy

  validates :name, presence: { message: "Имя темы не может быть пустым" },
  length: { in: 5..40, message: "В имени темы должно быть от 5 до 40 символов"},
  uniqueness: {case_sensitive: false, message: "Такое имя темы уже существует"}
  validates :content, presence: { message: "Тема не может быть пустой" },
  length: { in: 1..5000, message: "В теме должно быть от 1 до 5000 символов"}
  validates :user_id, presence: { message: "Тема должна принадлежать пользователю" }
  validates :forum_id, presence: { message: "Тема должна принадлежать форуму" }
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user_t, only: [:edit, :update, :destroy]

    def show
      @topic = Topic.find(params[:id])
      @messages = @topic.messages.all.paginate(:page => params[:page], :per_page => 20)
      if logged_in?
        @message = @topic.messages.new
      end
    end

    def new
      @topic = current_user.topics.new
    end

    def create
      @topic = current_user.topics.new(topic_params)
      if @topic.save
        flash[:success] = "Новая тема успешно создана!"
        redirect_to forum_url(params[:forum_id])
      else
        render 'new'
      end
    end

    def destroy
      Topic.find(params[:id]).destroy
      redirect_back fallback_location: forum_url(params[:forum_id])
    end

    def edit
      @topic = Topic.find(params[:id])
    end

    def update
      @topic = Topic.find(params[:id])

      if @topic.restricted != params[:topic][:restricted]
        @topic.messages.all.each do |m|
          m.update_attributes(update_params_m)
        end
      end

      if @topic.update_attributes(update_params)
        flash[:success] = "Тема успешно обновлена!"
        redirect_to forum_topic_url(@topic.forum_id, @topic)
      else
        render 'edit'
      end

    end

    private

    def topic_params
      t_params = params.require(:topic).permit(:name, :content)
      t_params[:forum_id] = params[:forum_id]
      f = Forum.find(params[:id]).restricted
      if f == "mod"
        t_params[:restricted] = :mod
      elsif t == "employee"
        t_params[:restricted] = :employee
      end
      t_params
    end

    def update_params
      t_params = params.require(:topic).permit(:name, :content, :restricted)
      t_params[:redacted_by] = current_user.id
      t_params
    end

    def update_params_m
      params.require(:topic).permit(:restricted)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def correct_user_t
    @user = User.find(Topic.find(params[:id]).user_id)
    unless ((@user == current_user) || @current_user.admin? || @current_user.mod?)
        flash[:danger] = "У вас нет прав доступа к этой страницы!"
        redirect_back fallback_location: forums_url
    end
  end
end

app/views/layouts/topic/_edit_form.html.erb
<div class="topic-edit-form">
  <%= form_for @topic, url: forum_topic_url(params[:forum_id], @topic), method: :patch do |f| %>

    <h2>Редактирование темы</h2>
    <div class="divider"></div>

    <%= render 'shared/error_messages/topic'%>

    <%= f.label :name, "Название темы:" %>
    <%= f.text_field :name %>

    <% if current_user.mod? || @current_user.admin? %>

    <%= f.label :restricted, "Только для:" %>
    <%= f.select :restricted, [["Модераторов", :mod ], ["Сотрудников", :employee], ["Для всех", :user]] %>

    <% end %>

    <%= f.label :content, "Текст:" %>
    <%= f.text_area :content %>

    <%= f.submit "Обновить тему" %>
  <% end %>
</div>

app/views/layouts/topic/_forum_topic_mini.html.erb
<% @topics.each do |t| %>
  <tr class="forum-topic-mini">

    <td>
      <%= link_to name_with_restriction(t), forum_topic_path(@forum, t) %>
    </td>
    <td><%= t.messages.count %></td>
    <td>
      <% u = User.find(t.user_id) %>
      <%= link_to u.name, user_path(u) %>
    </td>
    <td><%= t.created_at.strftime("%d/%m/%Y - %H:%M:%S") %></td>
  </tr>

<% end %>

app/views/layouts/topic/_new_form.html.erb
<div class="topic-new-form">
  <%= form_for @topic, url: forum_topics_url(params[:forum_id]) do |f| %>

  <h2>Создание темы</h2>
  <div class="divider"></div>

    <%= render 'shared/error_messages/topic' %>

    <%= f.label :name, "Название темы:" %>
    <%= f.text_field :name %>

    <% if current_user.mod? || @current_user.admin? %>

    <%= f.label :restricted, "Только для:" %>
    <%= f.select :restricted, [["Модераторов", :mod ], ["Сотрудников", :employee], ["Для всех", :user]] %>

    <% end %>

    <%= f.label :content, "Текст:" %>
    <%= f.text_area :content %>

    <%= f.submit "Создать тему" %>
  <% end %>
</div>

app/views/layouts/topic/_user_topic_mini.html.erb
<% @topics.each do |t| %>

<div class="topic-mini">

  <div class="topic-mini-heading">
    <%= name_with_restriction(t) %>
    <% if !t.redacted_by.nil? %>
      <div class="pop-up">
        <div class="pop-up-content">
          <span>Редактирована: <%= User.find(t.redacted_by).name %></span><br>
          <span>Дата: <%= t.updated_at.strftime("%d/%m/%Y - %H:%M:%S") %></span>
        </div>
        <div class="pop-up-trigger"></div>
      </div>
    <% end %>
  </div>

  <div class="topic-mini-body">
    <%= if (t.content.length <= 200)
      simple_format(t.content, {}, wrapper_tag: "span")
    else
      simple_format(t.content[0,199] + "...", {}, wrapper_tag: "span")
    end %>
  </div>

  <div class="topic-mini-footer">
    <div class="info">
      <% f = Forum.find(t.forum_id) %>
      <%= link_to name_with_restriction(f), forum_path(f) %>, <%= t.created_at.strftime("%d/%m/%Y - %H:%M:%S") %>
    </div>
    <% if current_user && (@current_user.admin? || @current_user.mod? || @current_user.id == t.user_id) %>
      <span>
        <%= link_to "Перейти", forum_topic_path(f, t) %>
        <%= link_to "Редактировать", edit_forum_topic_path(f, t) %>
        <%= link_to "Удалить", forum_topic_path(f, t), method: :delete, data: { confirm: "Вы уверены, что хотите удалить эту тему?"} %>
      </span>
    <% end %>
  </div>

</div>

<% end %>